from dashboard.components.test_component import test_component as test_component
from dashboard.components.navbar_component import navbar_component as navbar
from dashboard.components.highlight_item import highlight_item
from dashboard.components.home_component_debug import home_debug as home_debug
